export const START_GET_TUTORIALS = "START_TUTORIALS";
export const SUCCESS_TUTORIALS = "SUCCESS_TUTORIALS";
export const ERROR_TUTORIALS = "ERROR_TUTORIALS";
export const FILTER_TUTORIALS = "FILTER_TUTORIALS";
export const DELETE_TUTORIALS = "DELETE_TUTORIALS";
export const CREATE_TUTORIAL = "CREATE_TUTORIAL";



export const START_SEARCH_TUTORIALS = "START_SEARCH_TUTORIALS";
export const SUCCESS_SEARCH_TUTORIALS = "SUCCESS_SEARCH_TUTORIALS";
export const ERROR_SEARCH_TUTORIALS = "ERROR_SEARCH_TUTORIALS";

export const START_DELETE_TUTORIALS = "START_DELETE_TUTORIALS";
export const ERROR_DELETE_TUTORIALS = "ERROR_DELETE_TUTORIALS";


export const START_CREATE_TUTORIAL = "START_CREATE_TUTORIAL";
export const ERROR_CREATE_TUTORIAL = "ERROR_CREATE_TUTORIAL";


export const START_ACTIVE_TUTORIAL = "START_ACTIVE_TUTORIAL";


